---
- secret:
    name: SECRET_NETBOX_MANAGER
    data:
      PYPI_API_TOKEN: !encrypted/pkcs1-oaep
        - KHFsjgY2P2vPDilZLNdsv0IzEFmCVAJQYaTP69Pf3+SGGOLGhq2r5u66V4ZuATzoktvaw
          lCUCdr4hnv6BsbFVAGwPfrUQ6pKCsY/inzwbdwcflHC/8aoFlUYb8JiQ1U/109dgzfTKb
          DhE53KJnHZtg1NLBbZ1P1iNOuvaMvUw6i3851PSzTeFk7cwfmyV5tFDx6kTiQJB0ojvYS
          spfunAowaXmfTr2LpAkVo7GaE8zhZjLmDgzsBPsKSnWDhulNNNInEfPYewmG7Qp0VtdYA
          6eBis9kdekZLk5/RG7yf1mehiCs9CyqZpWDvGmwwGZOFA+V2LsjPmY2OMKMFsiyBvit2/
          +x8Aienq5YynPlOteiwgKGRD4zAyk8DkZ/YCUCjuvMUBQXRCdWWn4KIPnHlgV+Xr3mtMD
          MN9bC/Ta9nWXo+C2/Krxu5tQIiKKa3qdOply8tCo+USFbbxV4Yn5eiH4uk3V/Y1n1b7Hm
          Tpqw90fGsfVfT9REF3gI6LW/6W3PpjBmS2DV6zMN+lTCXm4mytafnXsm0gIwwEmzSvY/m
          cGleM35EdcA7BotPWblD1QhtejEqd/lZ0XBSvxGECeL6y6h+JmsVctbd/rdC1z3Xou3j0
          cPXh+4GdHuLqwT6d1uwp8VdCwD176LR+PGk3rcF1KtWHGCcNwekrhlpc1ge4CM=

- job:
    name: netbox-manager-publish-pypi-package
    parent: publish-pypi-package
    secrets:
      - name: secret
        secret: SECRET_NETBOX_MANAGER
        pass-to-parent: true
    vars:
      pypi_twine_executable: "/tmp/venv/bin/python -m twine"

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - mypy
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - flake8
        - mypy
        - python-black
        - yamllint
    tag:
      jobs:
        - netbox-manager-publish-pypi-package
